-- ---------------------------------------------------------------------------
-- Local copy of WHO's ICD-10 classification (code + title + URI per entry),
-- harvested once via WHO's ICD-API and stored here so doctors can search
-- ICD-10 by name from inside ClairMD. This exists because WHO's own API has
-- no free-text search for ICD-10 (only structured browse-by-code, and only
-- ICD-11 has real search) — see services/whoIcd.js's header comment for the
-- full trail of what was checked before landing on this approach, and why
-- it's licensed use under WHO's ICD-11 License Agreement Section 2.3
-- (incorporating the Classification into a computer application) rather
-- than distributing a standalone dataset.
--
-- Reference data only, not patient content — same category as this
-- database already holds (accounts/billing/referral/telemetry, per
-- pool.js's own comment), just sourced from WHO instead of generated by
-- ClairMD itself. Populated by db/harvestIcd10.js, not by the app at
-- request time; re-run periodically since ICD-10 is a largely frozen
-- WHO classification with only occasional updates.
-- ---------------------------------------------------------------------------

CREATE TABLE icd10_codes (
    code        TEXT PRIMARY KEY,
    title       TEXT NOT NULL,
    uri         TEXT NOT NULL,
    -- The chapter (top-level) code this entry lives under, and its direct
    -- parent's code in the tree — kept mainly for context/debugging the
    -- harvest, not required for search itself.
    chapter     TEXT,
    parent_code TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Name search is a plain ILIKE over ~14,000 rows — small enough that this
-- needs no special text-search index to stay fast.
CREATE INDEX idx_icd10_codes_title ON icd10_codes (title);
